update project
Ivnsol/java-filmorate pull request #4
Opened 2024-01-13 10:53 UTC by Ivnsol

2024-01-13 17:57 UTC, EugeneLenkevich requested changes
Привет, Иван! Спасибо за PR.

Отличная работа! :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

В первую очередь хотелось бы избавиться от запросов в цикле, остальное в принципе мелочи

2024-01-13 17:57 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmStorage.java
> +    List<Film.GenreWrapper> getGenre();
Film.GenreWrapper

Как то сложновато выглядит такой класс в методе интерфейса, будь то бы детали реализации, пусть лучше будет
Genre
Mpa

:)

2024-01-13 17:57 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            User users = userStorage.getUserById(integer);
users

Давай назовем переменную user, в единственном числе :)

2024-01-13 17:57 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                User user = userStorage.getUserById(integer);
Тут мы в цикле делаем запросы к БД, это не особо оптимально так как эта операция сама по себе достаточно дорогая и количество запросов лучше минимизировать. Вместо перебора ид можно использовать вот такой запрос типа такого

`select * from user where id in (...)`

где параметром будет служить коллекция ид

2024-01-13 17:57 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
>  public class InMemoryFilmStorage implements FilmStorage {
Эти хранилища можно вовсе, наверно, удалить чтобы не мешались.

2024-01-13 17:57 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmStorage.java
> +    Film updateFilm(Film film);
Вот смотри, объект называется FilmStorage, методы принимают/возвращают объекты типа Film, а что если убрать упоминание Film из названий методов, кажется что станет покороче без потери читаемости :)

2024-01-16 08:52 UTC, Ivnsol commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                User user = userStorage.getUserById(integer);
прописал отдельный метод запрос к бд для общих друзей

2024-01-17 17:02 UTC, EugeneLenkevich requested changes
Отметил один момент.
Далее, по схеме, по идее нам нужен внешний ключ, который свяжет лайки и юзеров

2024-01-17 17:02 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmStorageImpl.java
> +                "order by sum(user_id) desc " +
order by sum(user_id)

Не совсем понятно  зачем суммировать идентификаторы, тут наверно должен быть count(user_id)?

2024-01-17 17:04 UTC, EugeneLenkevich requested changes
.

2024-01-18 05:39 UTC, Ivnsol commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmStorageImpl.java
> +                "order by sum(user_id) desc " +
да, точно

2024-01-18 05:52 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2024-01-20 16:25 UTC, merged